// ─── Learning recommendation ────────────────────────────────────────────────────
// A recommendation generated by the engine — requires human approval before applying.

import type { LearningStatus } from './LearningTypes';
import type { LearningPattern } from './LearningPattern';

export type RecommendationType =
  | 'PARAMETER_ADJUSTMENT'
  | 'RULE_UPDATE'
  | 'THRESHOLD_CHANGE'
  | 'WEIGHT_RECALIBRATION'
  | 'PROCESS_IMPROVEMENT'
  | 'ESCALATION_CHANGE';

export type RecommendationPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface LearningRecommendation {
  recommendationId:   string;
  organizationId:     string;
  type:               RecommendationType;
  priority:           RecommendationPriority;
  title:              string;
  description:        string;
  /** Patterns that led to this recommendation. */
  sourcePatterns:     LearningPattern[];
  /** The specific change being recommended — never applied automatically. */
  proposedChange:     Record<string, unknown>;
  /** Expected impact of applying the recommendation. */
  expectedImpact:     string;
  /** Human-readable rationale. */
  rationale:          string;
  status:             LearningStatus;
  /** Who approved/rejected, if applicable. */
  reviewedBy:         string | null;
  reviewedAt:         string | null;
  reviewComment:      string | null;
  createdAt:          string;
  version:            string;
  /** Schema version for tracking recommendation evolution. */
  schemaVersion:      number;
}
