// ─── Decision type ──────────────────────────────────────────────────────────────

export type DecisionType =
  | 'STRATEGY_SELECTION'
  | 'RESOURCE_ALLOCATION'
  | 'PRIORITIZATION'
  | 'RISK_RESPONSE'
  | 'GO_NO_GO'
  | 'OPTIMIZATION_CHOICE'
  | 'FORECAST_BASED_DECISION'
  | 'RECOMMENDATION_SELECTION'
  | 'WORKFLOW_SELECTION'
  | 'ESCALATION'
  | 'HUMAN_APPROVAL_GATE';

export const DECISION_TYPES: readonly DecisionType[] = [
  'STRATEGY_SELECTION', 'RESOURCE_ALLOCATION', 'PRIORITIZATION', 'RISK_RESPONSE',
  'GO_NO_GO', 'OPTIMIZATION_CHOICE', 'FORECAST_BASED_DECISION',
  'RECOMMENDATION_SELECTION', 'WORKFLOW_SELECTION', 'ESCALATION',
  'HUMAN_APPROVAL_GATE',
] as const;
