import type { AgentDeclaration } from '../models.js';
import { AgentRegistry } from '../registry/AgentRegistry.js';

export function createAllAgents(): AgentDeclaration[] {
  return [
    {
      id: 'ceo',
      name: 'CEO Agent',
      role: 'Chief Executive Officer',
      description: 'Strategic decision-making, resource allocation, and high-level coordination across the organization.',
      capabilities: ['strategic-planning', 'resource-allocation', 'decision-making', 'escalation', 'priority-assessment'],
      tools: ['dashboard', 'reports', 'kpi-tracker'],
      connectors: ['salesforce', 'hubspot'],
      estimatedCostPerTask: 0.50,
      averageExecutionTimeMs: 200,
      confidence: 0.95,
      priority: 'critical',
      version: '2.0.0',
    },
    {
      id: 'sales',
      name: 'Sales Agent',
      role: 'Sales Manager',
      description: 'Manages leads, opportunities, customer relationships, and sales pipeline operations.',
      capabilities: ['lead-management', 'opportunity-tracking', 'customer-communication', 'pipeline-analysis', 'quoting'],
      tools: ['crm', 'email', 'quote-builder'],
      connectors: ['salesforce', 'hubspot'],
      estimatedCostPerTask: 0.30,
      averageExecutionTimeMs: 300,
      confidence: 0.88,
      priority: 'high',
      version: '2.0.0',
    },
    {
      id: 'finance',
      name: 'Finance Agent',
      role: 'Financial Controller',
      description: 'Handles payments, budgets, invoices, financial reporting, and cost analysis.',
      capabilities: ['payment-processing', 'budget-analysis', 'invoice-management', 'financial-reporting', 'cost-estimation'],
      tools: ['accounting', 'spreadsheet', 'banking-api'],
      connectors: ['salesforce'],
      estimatedCostPerTask: 0.40,
      averageExecutionTimeMs: 400,
      confidence: 0.92,
      priority: 'high',
      version: '2.0.0',
    },
    {
      id: 'support',
      name: 'Support Agent',
      role: 'Customer Support Specialist',
      description: 'Resolves customer incidents, tickets, inquiries, and manages support communications.',
      capabilities: ['incident-resolution', 'ticket-management', 'customer-communication', 'escalation', 'follow-up'],
      tools: ['helpdesk', 'email', 'chat'],
      connectors: ['slack', 'jira'],
      estimatedCostPerTask: 0.20,
      averageExecutionTimeMs: 250,
      confidence: 0.85,
      priority: 'high',
      version: '2.0.0',
    },
    {
      id: 'developer',
      name: 'Developer Agent',
      role: 'Software Developer',
      description: 'Writes, reviews, and tests code. Manages technical implementations and codebase changes.',
      capabilities: ['code-writing', 'code-review', 'testing', 'debugging', 'implementation'],
      tools: ['ide', 'git', 'test-runner'],
      connectors: ['github'],
      estimatedCostPerTask: 0.35,
      averageExecutionTimeMs: 500,
      confidence: 0.87,
      priority: 'normal',
      version: '2.0.0',
    },
    {
      id: 'devops',
      name: 'DevOps Agent',
      role: 'DevOps Engineer',
      description: 'Manages deployments, infrastructure, CI/CD pipelines, and system monitoring.',
      capabilities: ['deployment', 'infrastructure-management', 'ci-cd', 'monitoring', 'rollback'],
      tools: ['docker', 'kubernetes', 'ci-runner'],
      connectors: ['github'],
      estimatedCostPerTask: 0.45,
      averageExecutionTimeMs: 600,
      confidence: 0.90,
      priority: 'high',
      version: '2.0.0',
    },
    {
      id: 'marketing',
      name: 'Marketing Agent',
      role: 'Marketing Manager',
      description: 'Manages campaigns, content creation, social media, and marketing analytics.',
      capabilities: ['campaign-management', 'content-creation', 'social-media', 'analytics', 'audience-targeting'],
      tools: ['cms', 'social-scheduler', 'analytics-dashboard'],
      connectors: ['hubspot'],
      estimatedCostPerTask: 0.25,
      averageExecutionTimeMs: 350,
      confidence: 0.83,
      priority: 'normal',
      version: '2.0.0',
    },
    {
      id: 'document',
      name: 'Document Agent',
      role: 'Document Specialist',
      description: 'Generates, processes, and manages documents, contracts, and reports.',
      capabilities: ['document-generation', 'contract-management', 'report-generation', 'formatting', 'templates'],
      tools: ['word-processor', 'pdf-generator', 'template-engine'],
      connectors: ['google', 'notion'],
      estimatedCostPerTask: 0.15,
      averageExecutionTimeMs: 200,
      confidence: 0.89,
      priority: 'normal',
      version: '2.0.0',
    },
    {
      id: 'research',
      name: 'Research Agent',
      role: 'Research Analyst',
      description: 'Conducts market research, data analysis, competitive intelligence, and information gathering.',
      capabilities: ['market-research', 'data-analysis', 'competitive-analysis', 'information-gathering', 'trend-analysis'],
      tools: ['search', 'analytics', 'data-visualizer'],
      connectors: ['google'],
      estimatedCostPerTask: 0.20,
      averageExecutionTimeMs: 800,
      confidence: 0.82,
      priority: 'low',
      version: '2.0.0',
    },
    {
      id: 'compliance',
      name: 'Compliance Agent',
      role: 'Compliance Officer',
      description: 'Ensures regulatory compliance, audits processes, and validates legal requirements.',
      capabilities: ['compliance-checking', 'audit', 'regulatory-validation', 'risk-assessment', 'policy-enforcement'],
      tools: ['audit-trail', 'policy-engine', 'risk-calculator'],
      connectors: ['google'],
      estimatedCostPerTask: 0.35,
      averageExecutionTimeMs: 300,
      confidence: 0.94,
      priority: 'high',
      version: '2.0.0',
    },
  ];
}

export function createDefaultRegistry(): AgentRegistry {
  const registry = new AgentRegistry();
  for (const agent of createAllAgents()) {
    registry.register(agent);
  }
  return registry;
}
